### ISSUE TITLE
[Request] Dataset terms of use / Licence

### ISSUE THREAD

**Issue by bmaguireibm** [ProPrivacy/covid-19#1]
Hi, 

Thank you for your work compiling this data and making it available to the community.

I was not able to find any licence or terms of use for this data, are there any ? and if so would it be possible to add this detail to the repo ?
This would greatly simplify the process of getting approval for its use in my company. 

Thank you again.

**Comment by ProPrivacy** [comment]
Really sorry for the delayed response. I've added the license file (CC-BY-4.0). Free to use it however you see fit with attribution.

Sean


---- On Tue, 19 May 2020 17:34:27 +0100 Brian Maguire <notifications@github.com> wrote ----




Hi,

Thank you for your work compiling this data and making it available to the community.

I was not able to find any licence or terms of use for this data, are there any ? and if so would it be possible to add this detail to the repo ?
 This would greatly simplify the process of getting approval for its use in my company.
Thank you again.

**Comment by bmaguireibm** [comment]
That's brilliant! thanks for your help with this.
